
CREATE TABLE IF NOT EXISTS bookmark(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS comment(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    bookmark_id INT NOT NULL,
    comment VARCHAR(255) NOT NULL,
    FOREIGN KEY(bookmark_id) REFERENCES bookmark(id)
);
